### ISSUE TITLE
`bind` resize potentially harmful

### ISSUE THREAD

**Issue by stefanpenner** [trentmwillis/ember-singularity#10]
https://github.com/trentmwillis/ember-singularity-mixins/blob/master/addon/mixins/resize-handler.js#L21-L22

The following would be the same:

```
Ember.run.schedule('afterRender', this, this.get(RESIZE));
```
- is applied to `this`, resulting in the same behavior as `bind`

Which would result in us not needing to `this.set(RESIZE, boundResize)` during this lifecycle hook [here](https://github.com/trentmwillis/ember-singularity-mixins/blob/master/addon/mixins/resize-handler.js#L22)

**Comment by isao** [comment]
@stefanpenner those links point to a different repo, `trentmwillis/ember-singularity-mixins` fyi
