### ISSUE TITLE
consider non-global HANDLER_MAP

### ISSUE THREAD

**Issue by stefanpenner** [trentmwillis/ember-singularity#12]
https://github.com/trentmwillis/ember-singularity/blob/master/addon/services/unified-event-handler.js#L44

Currently all service instances (in test runs for example) will share the same HANDLER_MAP, this may result in unexpected behavior. Such as memory leaks.

If this is on the service instance we would be able to assert, that on `destroy` of the service we have cleaned up all handlers for that application instance. This would mitigate test leaks, due to unbalanced events.

Another approach, is to automatically unregister on destroy and not error.

**Comment by trentmwillis** [comment]
#14 fixes this.
