### ISSUE TITLE
Capability to unregister the scroll mixin

### ISSUE THREAD

**Issue by harrybui** [trentmwillis/ember-singularity#3]
Should support the ability to unregister the scroll callback when it is no longer needed. Right now I can call this.unregisterScrollHandlers() directly, but this will cause an JS error on the willDestroyElement event where it will try to unregister again.

**Comment by trentmwillis** [comment]
Opened a corresponding [issue in ember-singularity-mixins](https://github.com/trentmwillis/ember-singularity-mixins/issues/1) where the mixins are defined.
